---
- name: "interfaces: Ensure state of interfaces"
  block:
    - name: "panos_interfaces"
      include_tasks: "{{ role_path }}/includes/panos_interface.yaml"
      loop: "{{ panos_interfaces }}"
      loop_control:
        loop_var: panos_interface

  rescue:
    - name: "display message"
      fail:
        msg: "revert NOT IMPLEMENTED"
      when: panos_config_rollback_enabled
