- name: "security_rules: Validate entries spec"
  delegate_to: localhost
  validate_role_spec:
    spec: interface_spec.yaml
  loop: "{{ panos_interfaces }}"
  loop_control:
    loop_var: panos_interface

- name: "interfaces: Ensure state of a list of panos_interface spec"
  panos_interface:
    ip_address: "{{ provider.host }}"
    username: "{{ provider.username }}"
    password: "{{ provider.password }}"
    ip: "{{ panos_interface.ip | default(omit, true) }}"
    mode: "{{ panos_interface.mode | default(omit, true) }}"
    enable_dhcp: "{{ panos_interface.enable_dhcp | default(omit, true) }}"
    if_name: "{{ panos_interface.name }}"
    zone_name: "{{ panos_interface.zone | default('untrust') }}"
    create_default_route: "{{ panos_interface.default_route | default(omit, true) }}"
    state: "{{ panos_interface.state | default ('present') }}"
    commit: false
  loop: "{{ panos_interfaces }}"
  loop_control:
    loop_var: panos_interface