---
- name: initialize function
  include_tasks: includes/init.yaml

- name: set role supported functions
  set_fact:
    paloalto_panos_functions:
      - ping
      - interfaces
      - noop
      - objects
      - run
      - rules
      - system

- name: validate the requested function is supported
  fail:
    msg: "invalid function specified, expected one of {{ paloalto_panos_functions }}, got {{ function }}"
  when: function | default('noop') not in paloalto_panos_functions

- name: include function specific tasks and run
  include_tasks: "{{ function  | default('noop') }}.yaml"