- name: "panos_setup"
  block:
    - include_tasks: check.yaml
    - include_tasks: interfaces.yaml
    - include_tasks: objects.yaml
    - include_tasks: nat_rules.yaml
    - include_tasks: security_rules.yaml
  always:
    - include_tasls: commit.yaml
  rescue:
    - debug:
        msg: "There is no module for revert in PaloAlto"
        verbosity: 3
