- name: "nat_rules: Validate entries spec"
  delegate_to: localhost
  validate_role_spec:
    spec: nat_rules_spec.yaml
  loop: "{{ panos_nat_rules }}"
  loop_control:
    loop_var: panos_nat_rule

- name: "nat_rules: Ensure state of a list of panos_nat_rule"
  panos_nat_rule:
    ip_address: "{{ provider.host }}"
    username: "{{ provider.username }}"
    password: "{{ provider.password }}"
    operation: "add"
    rule_name: "{{ panos_nat_rule.rule_name }}"
    source_zone: "{{ panos_nat_rule.source_zone }}"
    destination_zone: "{{ panos_nat_rule.destination_zone }}"
    source_ip: "{{ panos_nat_rule.source_ip | default (omit) }}"
    destination_ip: "{{ panos_nat_rule.destination_ip | default (omit) }}"
    service: "{{ panos_nat_rule.service | default(omit) }}"
    snat_type: "{{ panos_nat_rule.snat_type | default (omit) }}"
    snat_interface: "{{ panos_nat_rule.snat_interface | default (omit) }}"
    dnat_address: "{{ panos_nat_rule.dnat_address | default(omit) }}"
    dnat_port: "{{ panos_nat_rule.dnat_port | default(omit) }}"
    state: "{{ panos_nat_rule.state | default ('present') }}"
    commit: false
  loop: "{{ panos_nat_rules }}"
  loop_control:
    loop_var: panos_nat_rule