---
- name: "objects: Ensure state of panos_address_objects"
  include_tasks: "includes/panos_address_object.yaml"
  loop: "{{ panos_address_objects }}"
  loop_control:
    loop_var: panos_address_object

- name: "objects: Ensure state of panos_service_objects"
  include_tasks: "includes/panos_service_object.yaml"
  loop: "{{ panos_service_objects }}"
  loop_control:
    loop_var: panos_service_object