- name: "check"
  include_tasks: check.yaml

- name: "panos_setup"
  block:
    - name: "system"
      include_tasks: system.yaml

    - name: "interfaces"
      include_tasks: interfaces.yaml

    - name: "objects"
      include_tasks: objects.yaml

    - name: "rules"
      include_tasks: rules.yaml

  rescue:
    - name: "display message"
      fail:
        msg: "revert NOT IMPLEMENTED"
      when: panos_config_rollback_enabled
