---
- name: "system: Ensure state of system"
  block:
    - name: "panos_system"
      include_tasks: "{{ role_path }}/includes/panos_mgtconfig.yaml"
      vars:
        panos_mgtconfig: "{{ panos_system }}"

  rescue:
    - name: "display message"
      fail:
        msg: "revert NOT IMPLEMENTED"
      when: panos_config_rollback_enabled
