---
argument_spec:

  ansible_network_os:
    description:
      - Set the name of the Ansible network OS platform.  This value should be
        set to `panos` for this provider.
    required: true

  config_manager_text:
    description:
      - Provide the network device configuration as a single string.  The
        configuration text will be loaded onto the target network deivce.
    type: str

  config_manager_file:
    description:
      - Provide a relative or absolute path to the configuration file to be
        loaded onto the target network device.
    type: str

required_one_of:
  - ['config_manager_text', 'config_manager_file']