---
- name: "initialize function"
  include_tasks: "{{ roles_path }}/includes/init.yaml"

- name: "validate role spec"
  validate_role_spec:
    spec: load_config_spec.yaml

- name: "create temp working dir"
  tempfile:
    state: directory
  register: panos_config_temp_dir

- name: "read config file to text"
  set_fact:
    config_manager_text: "{{ lookup('file', config_manager_file) }}"
  when: config_manager_file is defined

- name: "write the config text to disk"
  copy:
    content: "{{ config_manager_text }}"
    dest: "{{ panos_config_temp_dir.path }}/panos_config.xml"

- name: "configure target device"
  block:
    - name: "import configuration file to the device"
      include_tasks: "{{ roles_path }}/includes/panos_import.yaml"
      vars:
        panos_import_file: "{{ panos_config_temp_dir.path }}/panos_config.xml"
        panos_import_category: "configuration"

    - name: "load configuration file from the device"
      include_tasks: "{{ roles_path }}/includes/panos_loadcfg.yaml"
      vars:
        panos_loadcfg_file: "{{ r_panos_import.filename }}"

  rescue:
    - name: "display message"
      debug:
        msg: "error configuring device, starting rollback"
      when: panos_config_rollback_enabled

    - name: "display message"
      fail:
        msg: "rollback NOT IMPLEMENTED"
      when: panos_config_rollback_enabled

    - name: fail host due to config load error
      fail:
        msg: "error loading configuration onto target device"
  
  always:
    - name: "save configuration to ensure consitency"
      include_tasks: "{{ roles_path }}/includes/panos_commit.yaml"